GET https://localhost:4000/orders


###

POST https://localhost:4000/orders
Content-Type: application/json

{
  "customerName": "jeff G",
  "amount": 13
}


###

GET https://localhost:4000/openapi/v1.json

